
# Step 1: Use the base Node image
FROM node:16-alpine

# Step 2: Set the working directory
WORKDIR /app

# Step 3: Copy the package.json and package-lock.json first (for better layer caching)
COPY frontend/package*.json ./

# Step 4: Clean npm cache and install dependencies
RUN npm cache clean --force && npm install

# Step 5: Copy the rest of the frontend files
COPY frontend /app

# Step 6: Expose the application port
EXPOSE 3000

ENV  BACKEND_URL=http://0.0.0.0:4000

# Step 7: Run the application (assuming your entry point is index.js)
CMD ["npm", "start"]
